### ISSUE TITLE
Notation

### ISSUE THREAD

**Issue by emitanaka** [Sayani07/paper-gracsR#4]
I don't think the current notation describes well what you mean:

$$S^A_{x,y} = \sum_{j} D_{x,y}(A)$$

Perhaps something like:

$$S^A_{x,y} = \sum_{j\in A} D(x_j,y_j)$$
where D is the distance metric, x_j is the values filtered by granularity $j$ for observation $x$ (similar for $y$)?

**Comment by emitanaka** [comment]
Also I am not sure if I'd be inclined to do A*B for granularity combination. Maybe either A:B or A^B instead?

**Comment by Sayani07** [comment]
Well suggested. Changed now.
